import Head from 'next/head'

import { Roboto } from 'next/font/google'
import Navbar from '@/components/header/Navbar'
import Hero from '@/components/hero/Hero'


const roboto = Roboto({
  weight: ['300','400','500','700','900'],
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={roboto.className}>
        <Navbar />
        <Hero/>
      </main>
    </>
  )
}
